version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD:-default_root_password}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE:-default_database}
    ports:
      - "${MYSQLDB_LOCAL_PORT:-3306}:${MYSQLDB_DOCKER_PORT:-3306}"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT:-8080}:${SPRING_DOCKER_PORT:-8080}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT:-3306}/${MYSQLDB_DATABASE:-default_database}?useSSL=false",
        "spring.datasource.username" : "${MYSQLDB_USER:-default_user}",
        "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD:-default_root_password}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
